spring:
  profiles:
    active: EN,cat,dev
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: ymljdbc

---
spring:
  profiles: prod
guru:
  username: ProdUserName
  password: ProdPassword
  jdbcurl: Prodjdbc